### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by DarkoGNU** [hugo4715/KnockbackPlusPlus#3]
I run TacoSpigot 1.8.8 with the lasted development build of ProtocolLib. I get this error. My server log: [https://hastebin.com/fenuricalo.md](url)
EDIT: This bug also occurs on plain Spigot, but the plugin doesn't get disabled for some reason.

**Comment by hugo4715** [comment]
Hi,
I'll investigate this issue.
I might switch to Protocollib as TinyProtocol is not working on some version.

**Comment by hugo4715** [comment]
I switched the plugin to ProtocolLib
Can you tell me if your error is still present with that new version
New version link: [https://www.dropbox.com/s/wdpkhjm43uwegv9/knockbackplusplus-1.7.jar?dl=0](https://www.dropbox.com/s/wdpkhjm43uwegv9/knockbackplusplus-1.7.jar?dl=1)

I'll put this version on spigotmc if the bug is gone.

**Comment by DarkoGNU** [comment]
Yeah, I tested Taco, Paper and plain Spigot 1.8.8. Works fine. Sorry that it took me so long to respond... I think I have slight social phobia. I get stressed out every time before checking a thread online 😂

**Comment by hugo4715** [comment]
Ok cool.
I'll push this to spigotmc.
